### ISSUE TITLE
Integrate "Trip Complete" Function

### ISSUE THREAD

**Issue by jtraweek** [MaryamAlMansour/690#31]
Program function that marks a trip as completed in the database.
Add a Boolean field in Trip db model.

**Comment by ghost** [comment]
Added the boolean field and created a trip complete view to redirect back to the itinerary page. We may want to look into just having a checkbox to for the add/edit trip form. Then have the "mark complete" occur as part of the form submission.

**Comment by jtraweek** [comment]
Task updated: Integrate the trip complete function into the new edit trip template.

**Comment by ghost** [comment]
Implemented this as checkbox on the add/edit trip page.
